name: Cross Platform and Unit Tests

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12.x, 3.13.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run:  pytest tests/