name: Cross Platform and Unit Tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUTF8: "1"
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy conan nanobind pytest build twine delocate

      - name: Build wheel
        run: python -m build

      - name: Fix macOS wheel with delocate
        if: runner.os == 'macOS'
        run: |
          mkdir -p fixed_wheels
          delocate-wheel -w fixed_wheels -v dist/*.whl
          delocate-listdeps fixed_wheels/*.whl
          delocate-repair fixed_wheels/*.whl

      - name: Install built wheel
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            pip install fixed_wheels/*.whl
          else
            pip install dist/*.whl
          fi

      - name: Running Tests
        run:  pytest tests/