name: Cross Platform and Unit Tests

on: [pull_request, push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake
      
      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy conan nanobind pytest build twine delocate

      - name: Configure and install Conan dependencies
        shell: bash
        run: |
            # default if none exists
            conan profile new default --detect --force
            conan install . \
              --output-folder=build \
              --build=missing \
              --profile=default 

      - name: Build wheel
        run: python -m build

      - name: Install built wheel
        shell: bash
        run: pip install dist/*.whl

      - name: Running Tests
        run:  pytest tests/