name: Cross Platform and Unit Tests

on: [pull_request, push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Installing pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Running Tests
        run:  pytest tests/