name: Cross-Platform CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    env:
      PYTHONUTF8: "1"

    steps:
      - uses: actions/checkout@v4                            

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5                       
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest build twine delocate conan

      - name: Install Conan dependencies
        run: conan profile detect --force

      - name: Build & package (isolated)
        run: python -m build -w -o dist/

      - name: Install & test
        run: |
          pip install dist/*.whl
          python -m pytest ./tests
