name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    permissions:
      contents: write    
      packages: write    
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version build twine

      - name: Bump version (patch)
        id: bump
        run: |
          bump2version patch --allow-dirty --commit

      - name: Push version bump to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin main
      - name: Build distribution
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
